import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import "react-toastify/dist/ReactToastify.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Navbar } from "@/components/globle/navbar";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        variables: {
          colorPrimary: "#135D66",
          colorText: "#021928",
        },
      }}
    >
      <html lang="en">
        <body className={inter.className}>
          <Navbar />
          {children}
          <ToastContainer />
        </body>
      </html>
    </ClerkProvider>
  );
}
