import { Toaster } from "@/components/ui/toaster";
import { ToastContainer } from "react-toastify";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ToastContainer />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
